// All interface text lives here except `Save order` and `Edit`, which stay English by design.
export const strings = {
  brandSuffix: 'Snacks',
  teamHeader: (count) => `টিম · ${count}`,
  noOrderYet: 'এখনো অর্ডার নেই',
  orderSubtitle: (n, total, currency) => `${n}টি আইটেম · ${currency}${total}`,
  orderHeading: 'আজকের নাশতার অর্ডার',
  priceLine: (currency, price, total) => `${currency}${price} প্রতিটি · ${currency}${total} মোট`,
  addSnack: 'নাশতা যোগ করুন',
  customItem: 'কাস্টম আইটেম',
  customName: 'নাম',
  customQty: 'পরিমাণ',
  customPrice: 'দাম',
  customPriceOptional: 'দাম (ঐচ্ছিক)',
  dayOpen: 'খোলা',
  dayLocked: 'বন্ধ',
  tabOrder: 'অর্ডার',
  tabSummary: 'সারসংক্ষেপ',
  shoppingList: 'বাজারের তালিকা',
  grandTotal: 'সর্বমোট',
  noOrdersToday: 'এখনো কোনো অর্ডার নেই',
  whoIsOrdering: 'কে অর্ডার করছেন?',
  pickYourName: 'উপরে থেকে আপনার নাম বেছে নিন।',
  back: 'পেছনে',
  saved: 'সেভ হয়েছে',
  editingBadge: 'সম্পাদনা করা হচ্ছে',
  orderSavedFor: (name) => `${name}-এর অর্ডার সেভ হয়েছে`,
  orderCleared: 'অর্ডার মুছে ফেলা হয়েছে',
  clearMyOrder: 'নিজের অর্ডার মুছুন',
  addAtLeastOne: 'কমপক্ষে একটি আইটেম যোগ করুন',
  dayClosedNotice: 'আজকের জন্য অর্ডার বন্ধ করা হয়েছে',
  removeItem: (name) => `${name} বাতিল করুন`,
  itemNamePlaceholder: 'আইটেমের নাম',

  // summary
  itemName: 'আইটেম',
  quantity: 'পরিমাণ',
  unitPrice: 'দাম',
  lineTotal: 'মোট',
  orderedBy: 'যারা অর্ডার করেছেন',
  perPersonBreakdown: 'ব্যক্তিগত হিসাব',
  personalTotal: 'ব্যক্তিগত মোট',
  someUnpriced: '* কিছু আইটেমের দাম নির্ধারিত নেই',
  orderedCount: (ordered, total) => `${ordered}/${total} জন অর্ডার করেছেন`,
  orderedHeading: 'যারা অর্ডার করেছেন',
  notOrderedHeading: 'যারা এখনো অর্ডার করেননি',
  everyoneOrdered: 'সবাই অর্ডার করে ফেলেছেন 🎉',

  // admin
  admin: 'অ্যাডমিন',
  login: 'লগইন',
  logout: 'লগ আউট',
  loginAsAssistant: (assistant) => `${assistant} হিসেবে লগইন`,
  password: 'পাসওয়ার্ড',
  wrongPassword: 'পাসওয়ার্ড সঠিক নয়',
  addFoodItem: 'ফুড আইটেম যোগ করুন',
  newItemName: 'নতুন আইটেমের নাম',
  newItemPrice: 'দাম',
  add: 'যোগ করুন',
  addEmployee: 'কর্মী যোগ করুন',
  newEmployeeName: 'নতুন কর্মীর নাম',
  lockDay: 'অর্ডার বন্ধ করুন',
  unlockDay: 'অর্ডার চালু করুন',
  resetDay: 'রিসেট',
  resetConfirm: 'আজকের সব অর্ডার মুছে যাবে। আগে ডাউনলোড করে নিন। আবার চাপুন নিশ্চিত করতে।',
  downloadCsv: 'ডাউনলোড',
  adminPanel: 'অ্যাডমিন প্যানেল',
  close: 'বন্ধ করুন',
};
